import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile, assertRole, errorResponse } from "@/lib/auth";
import { invoiceCreateSchema } from "@/lib/validators";
import { buildInvoice } from "@/lib/invoice";
import { getBookingOr404, withTimeline } from "@/lib/booking-service.server";

const SNAP_FIELDS = ["address", "gst_number", "company", "mobile", "email"] as const;

// GET /api/invoices — tenant-scoped list
export async function GET() {
  const { user, profile, supabase } = await getSessionProfile();
  if (!user || !profile) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  const { data, error } = await supabase.from("invoices").select("*").order("created_at", { ascending: false }).limit(2000);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data);
}

// POST /api/invoices — generate from a booking (accounts / admin)
export async function POST(req: NextRequest) {
  try {
    const { user, profile, supabase } = await getSessionProfile();
    if (!user || !profile) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    assertRole(profile.role, ["accounts"]);

    const body = invoiceCreateSchema.parse(await req.json());
    const b = await getBookingOr404(supabase, body.booking_id);

    const { data: existing } = await supabase
      .from("invoices").select("id").eq("booking_id", body.booking_id).maybeSingle();
    if (existing) return NextResponse.json({ error: "Invoice already generated for this booking" }, { status: 400 });

    // customer (for service-charge rates) + company (prefix + terms)
    const { data: customer } = b.customer_id
      ? await supabase.from("customers").select("*").eq("id", b.customer_id).maybeSingle()
      : { data: null };
    const { data: company } = await supabase
      .from("company_settings").select("invoice_prefix, terms").eq("tenant_id", profile.tenant_id).maybeSingle();

    const { data: seq, error: seqErr } = await supabase.rpc("next_seq", { p_name: "invoice" });
    if (seqErr) return NextResponse.json({ error: seqErr.message }, { status: 500 });
    const prefix = company?.invoice_prefix || "INV";
    const number = `${prefix}-${new Date().getFullYear()}-${String(seq).padStart(6, "0")}`;

    const totals = buildInvoice(b, customer, body);

    const snapshot: Record<string, unknown> = { ...(b.customer_snapshot ?? {}) };
    if (customer) for (const k of SNAP_FIELDS) if (!snapshot[k]) snapshot[k] = customer[k] ?? null;

    const { data: inv, error: invErr } = await supabase
      .from("invoices")
      .insert({
        tenant_id: profile.tenant_id,
        invoice_number: number,
        booking_id: body.booking_id,
        booking_number: b.booking_number,
        customer: snapshot,
        passengers: b.passengers ?? [],
        items: totals.items,
        subtotal: totals.subtotal,
        discount: totals.discount,
        tax_rate: totals.tax_rate,
        gst_basis: totals.gst_basis,
        service_charge_total: totals.service_charge_total,
        tax_amount: totals.tax_amount,
        grand_total: totals.grand_total,
        amount_received: 0,
        balance_due: totals.grand_total,
        status: "Unpaid",
        notes: "",
        terms: body.terms || company?.terms || null,
        invoice_date: new Date().toISOString(),
        created_by: profile.name,
      })
      .select()
      .single();
    if (invErr) return NextResponse.json({ error: invErr.message }, { status: 500 });

    await supabase
      .from("bookings")
      .update({
        invoice_id: inv.id,
        status: "Invoice Generated",
        payment_status: "Unpaid",
        timeline: withTimeline(b.timeline, profile.name, `Invoice ${number} generated by Accounts`),
      })
      .eq("id", body.booking_id);

    await supabase.from("notifications").insert({
      tenant_id: profile.tenant_id,
      roles: ["sales", "accounts"],
      message: `Invoice ${number} generated for ${b.booking_number}`,
      booking_id: body.booking_id,
      booking_number: b.booking_number,
      read_by: [],
    });

    return NextResponse.json(inv);
  } catch (e) {
    return errorResponse(e);
  }
}
